### ISSUE TITLE
Date/Time formatting

### ISSUE THREAD

**Issue by rickardinho** [DRDD2016/app#201]
Hi @minaorangina 
We have had a discussion about the format of the date and time.
In the feed, we would like to drop the year from the date to reduce clutter, and only show year in the albums view (for past events).  We think this will be neater.
Also, we think we can remove time from the feed so that its just date that is shown.  Time will still be available when the user clicks to see the event details.

Finally, we think the time dropdown would be better displayed at 5 minute intervals rather than every minute as it is now... is this possible or is it standard functionality?

Dave
cc: @Dameodeare

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare I have implemented the 5 minute interval for the time dropdown and cleaned up the date in the feed.  Have a look and tell us what you think.  If you're happy, feel free to close this issue.

**Comment by minaorangina** [comment]
Just realised I haven't done it for the calendar.  I'll make those changes today

**Comment by rickardinho** [comment]
Hi @minaorangina.
The feed looks okay, as you say calendar needs changing, but I still see minute intervals in the dropdowns, not five-minute ones.  This is on Android.
Dave

**Comment by minaorangina** [comment]
@rickardinho Looked into this, so apparently the html attribute that makes time intervals possible isn't fully supported on mobile browsers (yet). 

A way around it would be to build a custom time picker.  The downside being you couldn't use the time picker that comes with the phone, somewhat reducing the native app feel.  Also, guaranteeing the custom picker would display properly on different phone sizes would need some time.  Let me know what you want to do.

**Comment by rickardinho** [comment]
@minaorangina Are there any existing time picker code snippets we can steal from existing apps?  I would think is a fairly common issue.  If we can do something quick then great, but I don't think we should prioritise it.  @Dameodeare do you agree?

**Comment by Dameodeare** [comment]
agree. we should steal a fix, or deprioritise.

**Comment by minaorangina** [comment]
@rickardinho @Dameodeare There are others that exist, built by other people.  But the quality of 3rd-party code snippets can be a mixed bag sometimes, I'd need to make sure it didn't clash with/break any of our own code.  

Probably best to revisit this later on in the sprint, after the higher-priority things are done.

**Comment by rickardinho** [comment]
Agreed @minaorangina
